apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines-ci-java
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: pipeline-ci
    server: 'https://kubernetes.default.svc'
  source:
    path: continuous-integration-repo/pipelines
    repoURL: https://github.com/davidseve/app-dev-ci-cd-poc.git
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false