apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "java.fullname" . }}-configmap-env"
  labels:
    {{- include "java.labels" . | nindent 4 }}
data:
  application.version: {{ .Values.image.tag }}
  application.colour: {{ .Values.version }}
  application.mode: {{ .Values.mode }}   
  quarkus.log.level: {{ .Values.log.level }}