{{ if .Values.router.enabled  }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "java.labels" . | nindent 4 }}
  name: {{ include "java.fullname" . }}
spec:
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ include "java.fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{ end }}