apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: java-binding
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-revision
    value: $(body.head_commit.id)
  - name: git-repo-name
    value: $(body.repository.name)    