apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: pipeline-ci
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/patch: |
      - op: add
        path: /secrets/-
        value:
          name: quay-pull-secret
secrets:
  - name: quay-pull-secret