apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: pipeline-ci
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true    
secret:
  - name: quay-pull-secret